name: Node.js Matrix Test
on:
  workflow_dispatch:

jobs:
  job_1:
    strategy:
        fail-fast: false
        max-parallel: 3
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            node-version: [14.x,15.x,18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
