name: Commands workflow
on:
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        deprecated=true
        if [[ depreacted ]]; then
          echo ::warning:: Deprecated fuction found
        fi 