name: Scheduled Workflow
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 min
      
jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "This is a scheduled task running every 5 min"