name: Scheduled Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'  # Every min at sunday
      
jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "This is a scheduled task running every min"